repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.4.4  # or the latest version
    hooks:
      - id: ruff

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0  # or your preferred version
    hooks:
      - id: mypy
        args: ["--strict"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
