"""
Keyboard dialog for adding/editing keyboards.
"""

from typing import Optional

from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import (
    QDialog,
    QDialogButtonBox,
    QFormLayout,
    QLineEdit,
    QMessageBox,
    QVBoxLayout,
    QWidget,
)

from models.keyboard import Keyboard


class KeyboardDialog(QDialog):
    """
    Dialog for adding or editing a keyboard.
    """

    def __init__(
        self,
        user_id: str,
        keyboard: Optional[Keyboard] = None,
        parent: Optional[QWidget] = None,
    ) -> None:
        """
        Initialize the keyboard dialog.

        Args:
            user_id: ID of the user this keyboard belongs to.
            keyboard: Optional keyboard to edit. If None, create a new keyboard.
            parent: Parent widget.
        """
        super().__init__(parent)
        self.user_id = user_id
        self.keyboard = keyboard
        self.setWindowTitle("Edit Keyboard" if keyboard else "Add Keyboard")
        self.setMinimumWidth(400)
        self.setup_ui()

    def setup_ui(self) -> None:
        """Set up the user interface."""
        layout = QVBoxLayout(self)

        # Form layout for keyboard details
        form_layout = QFormLayout()

        # Keyboard name field
        self.name_edit = QLineEdit()
        self.name_edit.setPlaceholderText("Enter keyboard name")
        form_layout.addRow("Keyboard Name:", self.name_edit)

        # Populate fields if editing
        if self.keyboard:
            self.name_edit.setText(self.keyboard.keyboard_name or "")

        layout.addLayout(form_layout)

        # Dialog buttons
        self.button_box = QDialogButtonBox(
            QDialogButtonBox.StandardButton.Ok | QDialogButtonBox.StandardButton.Cancel
        )
        self.button_box.accepted.connect(self.validate_and_accept)
        self.button_box.rejected.connect(self.reject)
        layout.addWidget(self.button_box)

    def validate_and_accept(self) -> None:
        """Validate input and accept the dialog if valid."""
        name = self.name_edit.text().strip()

        if not name:
            QMessageBox.warning(self, "Validation Error", "Keyboard name is required.")
            self.name_edit.setFocus()
            return

        # Create or update keyboard object
        if self.keyboard:
            self.keyboard.keyboard_name = name
        else:
            self.keyboard = Keyboard(
                keyboard_id="",  # Will be generated by the manager
                user_id=self.user_id,
                keyboard_name=name,
            )

        self.accept()

    def get_keyboard(self) -> Keyboard:
        """
        Get the keyboard object with updated values.

        Returns:
            The updated or new keyboard object.
        """
        return self.keyboard
